export const AppRoutes = {
  home: "/",
  game: "/game",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  profile: "/profile",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminLocations: "/admin/locations",
  adminLocationCreate: "/admin/locations/create",
  adminLocationEdit: (id: string) => `/admin/locations/${id}/edit`,
} as const;
